version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.redisson:redisson
    versions:
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.eclipse.jetty:jetty-http
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 11.0.0
  - dependency-name: org.apache.maven.wagon:wagon-provider-api
    versions:
    - 3.4.2
  - dependency-name: biz.aQute.bnd:bnd-maven-plugin
    versions:
    - 5.2.0
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
